package com.notes.notes.core

import java.util.Locale

data class CommonStrings(
    val login: String,
    val register: String,
    val logout: String,
    val light: String,
    val dark: String,
    val system: String,
    val confirm: String,
    val cancel: String,
    val close: String,
    val create: String,
    val upload: String,
    val refresh: String,
    val language: String,
    val actions: String,
    val name: String,
    val retry: String,
    val loading: String,
    val baseUrl: String,
    val baseUrlMissing: String,
    val networkError: String,
    val forbidden: String,
    val unauthorized: String,
    val badRequest: String,
    val apiNotFound: String,
    val serverError: String,
    val unknownError: String,
    val enUs: String,
    val zhCn: String,
)

data class NavStrings(
    val title: String,
    val disk: String,
    val read: String,
    val account: String,
    val guest: String,
    val online: String,
    val offline: String,
)

data class ThemeStrings(
    val switchToLight: String,
    val switchToDark: String,
    val settingsTitle: String,
    val settingsDescription: String,
    val currentTheme: String,
    val mode: String,
    val palette: String,
    val eyeCarePalette: String,
    val blue: String,
    val emerald: String,
    val amber: String,
    val rose: String,
    val sage: String,
    val almond: String,
)

data class AuthStrings(
    val username: String,
    val password: String,
    val confirmPassword: String,
    val loginButton: String,
    val autoLogin: String,
    val registerButton: String,
    val loginFirst: String,
    val incorrectCredentials: String,
    val unauthorized: String,
    val badRequest: String,
    val apiNotFound: String,
    val serverError: String,
    val unknownSuccessError: String,
    val unknownError: String,
    val networkError: String,
)

data class AccountStrings(
    val changePassword: String,
    val deleteAccount: String,
    val logout: String,
    val language: String,
    val logoutButton: String,
    val logoutPanelDescription: String,
    val currentAccount: String,
    val languagePanelTitle: String,
    val languagePanelDescription: String,
    val currentLanguage: String,
    val signedInAsTemplate: String,
)

data class ChangePasswordStrings(
    val curPassword: String,
    val newPassword: String,
    val confirmPassword: String,
    val mismatch: String,
    val warning: String,
    val submit: String,
)

data class DeleteAccountStrings(
    val curPassword: String,
    val warning: String,
    val confirmFirst: String,
    val modalTitle: String,
    val modalBody: String,
    val confirmSecond: String,
)

data class FileDiskStrings(
    val root: String,
    val uploadTitle: String,
    val uploadTypeDirectory: String,
    val uploadTypeFile: String,
    val createFolderTitle: String,
    val uploadFilesTitle: String,
    val pickFiles: String,
    val dirName: String,
    val create: String,
    val uploadPrompt: String,
    val uploadTip: String,
    val creationTime: String,
    val lastModified: String,
    val created: String,
    val updated: String,
    val openUploadDialog: String,
    val refreshDirectory: String,
    val renameDirectory: String,
    val deleteDirectory: String,
    val renameFile: String,
    val deleteFile: String,
    val downloadFile: String,
    val changeDirectoryPrompt: String,
    val changeDirectoryTitle: String,
    val changeFilePrompt: String,
    val changeFileTitle: String,
    val renameCurrentName: String,
    val renameNewName: String,
    val renameDirectoryHint: String,
    val renameFileHint: String,
    val deleteDialogWarning: String,
    val deleteTargetName: String,
    val deleteDirectoryPrompt: String,
    val deleteFilePrompt: String,
    val emptyText: String,
    val invalidDirectoryName: String,
    val inputCanceled: String,
    val deleted: String,
    val renamed: String,
    val welcomeBack: String,
    val directoryLoading: String,
    val directoryLoadFailed: String,
    val directoryEmpty: String,
    val sortAscending: String,
    val sortDescending: String,
    val sortByColumnTemplate: String,
    val sortByColumnWithDirectionTemplate: String,
    val sortOptionsTitle: String,
    val sortCurrentLabelTemplate: String,
    val sortNameAscending: String,
    val sortNameDescending: String,
    val sortCreationNewest: String,
    val sortCreationOldest: String,
    val sortModifiedNewest: String,
    val sortModifiedOldest: String,
    val overwriteSameName: String,
    val noFileSelected: String,
    val uploadSuccessTemplate: String,
    val uploadFailedTemplate: String,
    val selected: String,
    val downloadStarted: String,
    val downloadCompleted: String,
    val uploadSelectionCountTemplate: String,
    val emptySelectionHint: String,
    val deleteDownloadedFilePrompt: String,
)

data class ReadingStrings(
    val emptyState: String,
    val refreshHint: String,
    val loadingPreview: String,
    val unsupportedFileType: String,
    val previewLoadFailed: String,
    val markdownLoadFailed: String,
    val selectFileFirst: String,
    val refreshToLoad: String,
    val officePreviewFallback: String,
)

data class AppStrings(
    val common: CommonStrings,
    val nav: NavStrings,
    val theme: ThemeStrings,
    val auth: AuthStrings,
    val account: AccountStrings,
    val changePassword: ChangePasswordStrings,
    val deleteAccount: DeleteAccountStrings,
    val fileDisk: FileDiskStrings,
    val reading: ReadingStrings,
) {
    fun httpErrorMessage(status: Int, authRequest: Boolean = false): String {
        val bucket = if (authRequest) auth else null
        return when (status) {
            400 -> bucket?.badRequest ?: common.badRequest
            401 -> bucket?.unauthorized ?: common.unauthorized
            403 -> bucket?.incorrectCredentials ?: common.forbidden
            404 -> bucket?.apiNotFound ?: common.apiNotFound
            500 -> bucket?.serverError ?: common.serverError
            0 -> bucket?.networkError ?: common.networkError
            else -> bucket?.unknownError ?: common.unknownError
        }
    }

    fun format(template: String, locale: Locale, vararg args: Any?): String = String.format(locale, template, *args)
}

fun ThemePalette.label(strings: AppStrings): String = when (this) {
    ThemePalette.BLUE -> strings.theme.blue
    ThemePalette.EMERALD -> strings.theme.emerald
    ThemePalette.AMBER -> strings.theme.amber
    ThemePalette.ROSE -> strings.theme.rose
    ThemePalette.SAGE -> strings.theme.sage
    ThemePalette.ALMOND -> strings.theme.almond
}

fun ThemeMode.label(strings: AppStrings): String = when (this) {
    ThemeMode.SYSTEM -> strings.common.system
    ThemeMode.LIGHT -> strings.common.light
    ThemeMode.DARK -> strings.common.dark
}

fun AppLanguage.label(strings: AppStrings): String = when (this) {
    AppLanguage.EN_US -> strings.common.enUs
    AppLanguage.ZH_CN -> strings.common.zhCn
}

fun stringsFor(language: AppLanguage): AppStrings = when (language) {
    AppLanguage.ZH_CN -> AppStrings(
        common = CommonStrings(
            login = "登录",
            register = "注册",
            logout = "退出登录",
            light = "浅色",
            dark = "深色",
            system = "跟随系统",
            confirm = "确认",
            cancel = "取消",
            close = "关闭",
            create = "创建",
            upload = "上传",
            refresh = "刷新",
            language = "语言",
            actions = "操作",
            name = "名称",
            retry = "重试",
            loading = "加载中",
            baseUrl = "BASE_URL",
            baseUrlMissing = "当前尚未配置 BASE_URL，请先在 local.properties 中设置 notes.baseUrl",
            networkError = "网络错误",
            forbidden = "没有权限执行此操作",
            unauthorized = "未授权，请重新登录",
            badRequest = "请求参数错误",
            apiNotFound = "接口不存在",
            serverError = "服务器内部错误，请稍后重试",
            unknownError = "未知错误，请联系管理员（resp-error-error）",
            enUs = "English",
            zhCn = "简体中文",
        ),
        nav = NavStrings(
            title = "笔记空间",
            disk = "云盘",
            read = "阅读",
            account = "设置",
            guest = "访客",
            online = "已登录",
            offline = "访客模式",
        ),
        theme = ThemeStrings(
            switchToLight = "切换到浅色模式",
            switchToDark = "切换到深色模式",
            settingsTitle = "主题设置",
            settingsDescription = "选择主题配色，并在浅色、深色和跟随系统之间切换。设置会保存在当前设备上",
            currentTheme = "当前主题",
            mode = "明暗模式",
            palette = "主题配色",
            eyeCarePalette = "护眼主题",
            blue = "默认蓝",
            emerald = "翡翠绿",
            amber = "琥珀色",
            rose = "玫瑰色",
            sage = "鼠尾草",
            almond = "杏仁色",
        ),
        auth = AuthStrings(
            username = "用户名",
            password = "密码",
            confirmPassword = "确认密码",
            loginButton = "登录",
            autoLogin = "自动登录",
            registerButton = "注册",
            loginFirst = "请先登录",
            incorrectCredentials = "用户名或密码错误",
            unauthorized = "未授权，请重新登录",
            badRequest = "请求参数错误",
            apiNotFound = "接口不存在",
            serverError = "服务器内部错误，请稍后重试",
            unknownSuccessError = "未知错误，请联系管理员（resp-success-error）",
            unknownError = "未知错误，请联系管理员（resp-error-error）",
            networkError = "网络错误",
        ),
        account = AccountStrings(
            changePassword = "修改密码",
            deleteAccount = "删除账户",
            logout = "退出登录",
            language = "语言设置",
            logoutButton = "退出登录",
            logoutPanelDescription = "结束当前设备上的登录状态，并返回到登录入口",
            currentAccount = "当前账户",
            languagePanelTitle = "语言设置",
            languagePanelDescription = "选择应用显示语言，设置会保存在当前设备上",
            currentLanguage = "当前语言",
            signedInAsTemplate = "当前登录：%s",
        ),
        changePassword = ChangePasswordStrings(
            curPassword = "原密码",
            newPassword = "新密码",
            confirmPassword = "确认密码",
            mismatch = "两次输入的密码不一致",
            warning = "出于安全原因，修改密码后需要重新登录",
            submit = "确认修改",
        ),
        deleteAccount = DeleteAccountStrings(
            curPassword = "当前密码",
            warning = "确定要删除这个账户吗？删除后所有信息都会被清除",
            confirmFirst = "确认删除",
            modalTitle = "二次确认",
            modalBody = "请再次确认，删除后的账户无法恢复",
            confirmSecond = "确认删除",
        ),
        fileDisk = FileDiskStrings(
            root = "根目录",
            uploadTitle = "上传",
            uploadTypeDirectory = "文件夹",
            uploadTypeFile = "文件",
            createFolderTitle = "创建文件夹",
            uploadFilesTitle = "上传文件",
            pickFiles = "选取",
            dirName = "文件夹名称",
            create = "创建",
            uploadPrompt = "点击选择文件，支持多选",
            uploadTip = "上传仍沿用原网页端的 OSS STS 流程",
            creationTime = "创建时间",
            lastModified = "最后修改",
            created = "创建于",
            updated = "更新于",
            openUploadDialog = "打开上传窗口",
            refreshDirectory = "刷新当前目录",
            renameDirectory = "重命名文件夹",
            deleteDirectory = "删除文件夹",
            renameFile = "重命名文件",
            deleteFile = "删除文件",
            downloadFile = "下载文件",
            changeDirectoryPrompt = "请输入新的文件夹名称",
            changeDirectoryTitle = "重命名文件夹",
            changeFilePrompt = "请输入新的文件名",
            changeFileTitle = "重命名文件",
            renameCurrentName = "当前名称",
            renameNewName = "新的名称",
            renameDirectoryHint = "名称不能为空，且不能使用 root 或 root_parent",
            renameFileHint = "名称不能为空",
            deleteDialogWarning = "请确认目标名称，删除后将无法撤销",
            deleteTargetName = "即将删除",
            deleteDirectoryPrompt = "文件夹删除后会立即从当前目录中移除，请谨慎操作",
            deleteFilePrompt = "文件删除后将无法继续在当前目录中使用，请谨慎操作",
            emptyText = "内容不能为空",
            invalidDirectoryName = "该名称不允许使用",
            inputCanceled = "已取消输入",
            deleted = "已删除",
            renamed = "已重命名",
            welcomeBack = "欢迎回来",
            directoryLoading = "加载中...",
            directoryLoadFailed = "加载失败，请刷新后重试",
            directoryEmpty = "这里什么都没有",
            sortAscending = "升序",
            sortDescending = "降序",
            sortByColumnTemplate = "按 %s 排序",
            sortByColumnWithDirectionTemplate = "按 %s 排序（当前：%s）",
            sortOptionsTitle = "排序方式",
            sortCurrentLabelTemplate = "当前：%s",
            sortNameAscending = "名称升序",
            sortNameDescending = "名称降序",
            sortCreationNewest = "创建时间最新优先",
            sortCreationOldest = "创建时间最旧优先",
            sortModifiedNewest = "修改时间最新优先",
            sortModifiedOldest = "修改时间最旧优先",
            overwriteSameName = "将覆盖同名文件",
            noFileSelected = "未选择文件",
            uploadSuccessTemplate = "上传成功：%s",
            uploadFailedTemplate = "上传失败：%s",
            selected = "已选中，前往阅读页后点击刷新即可预览",
            downloadStarted = "已开始下载",
            downloadCompleted = "下载完成",
            uploadSelectionCountTemplate = "已选择 %d 个文件",
            emptySelectionHint = "尚未选择任何文件",
            deleteDownloadedFilePrompt = "删除后将从 Download/Notes 中移除",
        ),
        reading = ReadingStrings(
            emptyState = "请选择一个文件开始阅读",
            refreshHint = "支持 PDF、Markdown、Word、Excel 和 PPT 预览，点击刷新开始加载",
            loadingPreview = "正在准备预览...",
            unsupportedFileType = "暂不支持该文件类型",
            previewLoadFailed = "预览加载失败，请稍后重试",
            markdownLoadFailed = "Markdown 加载失败",
            selectFileFirst = "请先在云盘页选中文件",
            refreshToLoad = "选中文件后，点击右上角刷新开始预览",
            officePreviewFallback = "这里使用结构化文档预览，以兼顾 Android 端稳定性",
        ),
    )

    AppLanguage.EN_US -> AppStrings(
        common = CommonStrings(
            login = "Login",
            register = "Register",
            logout = "Log out",
            light = "Light",
            dark = "Dark",
            system = "Follow system",
            confirm = "Confirm",
            cancel = "Cancel",
            close = "Close",
            create = "Create",
            upload = "Upload",
            refresh = "Refresh",
            language = "Language",
            actions = "Actions",
            name = "Name",
            retry = "Retry",
            loading = "Loading",
            baseUrl = "BASE_URL",
            baseUrlMissing = "BASE_URL is not configured yet. Add notes.baseUrl to local.properties first.",
            networkError = "Network error.",
            forbidden = "You do not have permission to perform this action.",
            unauthorized = "Unauthorized, please login again.",
            badRequest = "Bad request.",
            apiNotFound = "API not found.",
            serverError = "Internal server error, please try again later.",
            unknownError = "Unknown error. Please contact the administrator (resp-error-error).",
            enUs = "English",
            zhCn = "简体中文",
        ),
        nav = NavStrings(
            title = "Notes Space",
            disk = "Disk",
            read = "Read",
            account = "Settings",
            guest = "Guest",
            online = "Signed in",
            offline = "Guest mode",
        ),
        theme = ThemeStrings(
            switchToLight = "Switch to light mode",
            switchToDark = "Switch to dark mode",
            settingsTitle = "Theme settings",
            settingsDescription = "Choose a theme palette, then switch between light, dark, and follow-system modes. The setting will be saved on this device.",
            currentTheme = "Current theme",
            mode = "Mode",
            palette = "Palette",
            eyeCarePalette = "Eye-care themes",
            blue = "Default blue",
            emerald = "Emerald",
            amber = "Amber",
            rose = "Rose",
            sage = "Sage",
            almond = "Almond",
        ),
        auth = AuthStrings(
            username = "Username",
            password = "Password",
            confirmPassword = "Confirm Password",
            loginButton = "Login",
            autoLogin = "Auto login",
            registerButton = "Register",
            loginFirst = "Please login first.",
            incorrectCredentials = "Incorrect username or password.",
            unauthorized = "Unauthorized, please login again.",
            badRequest = "Bad request.",
            apiNotFound = "API not found.",
            serverError = "Internal server error, please try again later.",
            unknownSuccessError = "Unknown error. Please contact the administrator (resp-success-error).",
            unknownError = "Unknown error. Please contact the administrator (resp-error-error).",
            networkError = "Network error.",
        ),
        account = AccountStrings(
            changePassword = "Change password",
            deleteAccount = "Delete account",
            logout = "Log out",
            language = "Language",
            logoutButton = "Log out",
            logoutPanelDescription = "End the session on this device and return to the account entry page.",
            currentAccount = "Current account",
            languagePanelTitle = "Language settings",
            languagePanelDescription = "Choose the display language for this app. The setting will be saved on this device.",
            currentLanguage = "Current language",
            signedInAsTemplate = "Signed in as %s",
        ),
        changePassword = ChangePasswordStrings(
            curPassword = "Original Password",
            newPassword = "New Password",
            confirmPassword = "Confirm Password",
            mismatch = "The two passwords do not match.",
            warning = "For security reasons, you will need to log in again after changing your password.",
            submit = "Confirm changes",
        ),
        deleteAccount = DeleteAccountStrings(
            curPassword = "Current Password",
            warning = "Are you sure you want to delete this account? All your information will be deleted!",
            confirmFirst = "Confirm deletion",
            modalTitle = "Second confirmation",
            modalBody = "Please confirm again. Deleted accounts cannot be recovered.",
            confirmSecond = "Confirm deletion",
        ),
        fileDisk = FileDiskStrings(
            root = "Root",
            uploadTitle = "Upload",
            uploadTypeDirectory = "Folder",
            uploadTypeFile = "File",
            createFolderTitle = "Create folder",
            uploadFilesTitle = "Upload files",
            pickFiles = "Pick",
            dirName = "Folder name",
            create = "Create",
            uploadPrompt = "Tap to pick files. Multiple selection is supported.",
            uploadTip = "Uploads still follow the original OSS STS workflow from the web app.",
            creationTime = "Creation Time",
            lastModified = "Last Modified",
            created = "Created",
            updated = "Updated",
            openUploadDialog = "Open upload dialog",
            refreshDirectory = "Refresh current directory",
            renameDirectory = "Rename folder",
            deleteDirectory = "Delete folder",
            renameFile = "Rename file",
            deleteFile = "Delete file",
            downloadFile = "Download file",
            changeDirectoryPrompt = "Enter the new folder name.",
            changeDirectoryTitle = "Rename folder",
            changeFilePrompt = "Enter the new file name.",
            changeFileTitle = "Rename file",
            renameCurrentName = "Current name",
            renameNewName = "New name",
            renameDirectoryHint = "The name cannot be empty, and root or root_parent are not allowed.",
            renameFileHint = "The name cannot be empty.",
            deleteDialogWarning = "Please verify the target name. This action cannot be undone.",
            deleteTargetName = "About to delete",
            deleteDirectoryPrompt = "The folder will be removed from the current directory immediately.",
            deleteFilePrompt = "The file will no longer be available from the current directory.",
            emptyText = "Empty text.",
            invalidDirectoryName = "This name is not allowed.",
            inputCanceled = "Input canceled",
            deleted = "Deleted",
            renamed = "Renamed",
            welcomeBack = "Welcome back.",
            directoryLoading = "Loading...",
            directoryLoadFailed = "Failed to load. Please refresh and try again.",
            directoryEmpty = "There is nothing here.",
            sortAscending = "Ascending",
            sortDescending = "Descending",
            sortByColumnTemplate = "Sort by %s",
            sortByColumnWithDirectionTemplate = "Sort by %s (current: %s)",
            sortOptionsTitle = "Sort options",
            sortCurrentLabelTemplate = "Current: %s",
            sortNameAscending = "Name ascending",
            sortNameDescending = "Name descending",
            sortCreationNewest = "Creation time newest first",
            sortCreationOldest = "Creation time oldest first",
            sortModifiedNewest = "Last modified newest first",
            sortModifiedOldest = "Last modified oldest first",
            overwriteSameName = "A file with the same name will be overwritten.",
            noFileSelected = "No file selected.",
            uploadSuccessTemplate = "Upload success: %s",
            uploadFailedTemplate = "Upload failed: %s",
            selected = "Selected. Go to the reader and tap refresh to preview it.",
            downloadStarted = "Download has started.",
            downloadCompleted = "Download completed.",
            uploadSelectionCountTemplate = "%d file(s) selected",
            emptySelectionHint = "No files selected yet",
            deleteDownloadedFilePrompt = "The file will be removed from Download/Notes.",
        ),
        reading = ReadingStrings(
            emptyState = "Select a file to start reading",
            refreshHint = "PDF, Markdown, Word, Excel, and PPT previews are supported. Tap refresh to load.",
            loadingPreview = "Preparing preview...",
            unsupportedFileType = "This file type is not supported.",
            previewLoadFailed = "Failed to load the previewer. Please try again later.",
            markdownLoadFailed = "Markdown failed to load.",
            selectFileFirst = "Select a file in Disk first.",
            refreshToLoad = "After selecting a file, tap refresh in the top-right corner to preview it.",
            officePreviewFallback = "A structured office preview is used here for stability on Android.",
        ),
    )
}
